# Generated by Django 4.1.10 on 2023-08-18 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("voice", models.CharField(max_length=200, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("final_video_asset", models.CharField(max_length=500, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("narration", models.TextField(null=True)),
                ("image_desc", models.TextField(null=True)),
                ("script", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectAssets",
            fields=[
                (
                    "scene_id",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="videogenerator.scene",
                    ),
                ),
                ("asset_path", models.JSONField(null=True)),
                ("currently_used_asset", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="videogenerator.request",
                    ),
                ),
                ("script_scenes", models.JSONField(default=list)),
                ("current_scenes", models.JSONField(default=list)),
            ],
            options={
                "unique_together": {("request",)},
            },
        ),
        migrations.CreateModel(
            name="PendingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(max_length=1000)),
                ("folder", models.CharField(max_length=255)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videogenerator.request",
                    ),
                ),
            ],
            options={
                "unique_together": {("request", "folder")},
            },
        ),
    ]
