# Generated by Django 4.1.10 on 2023-07-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videogenerator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingtask",
            old_name="img_desc",
            new_name="prompt",
        ),
    ]
