# Generated by Django 4.2.3 on 2023-07-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogenerator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="voice",
            field=models.IntegerField(null=True),
        ),
    ]
