# Generated by Django 4.1.10 on 2023-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogenerator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="final_video_asset",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
