# Generated by Django 4.2.3 on 2023-07-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogenerator", "0002_alter_request_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="script",
            field=models.TextField(null=True),
        ),
    ]
