# Generated by Django 4.1.10 on 2023-08-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogenerator", "0002_request_final_video_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="script",
            field=models.UUIDField(),
        ),
    ]
