# Generated by Django 4.2.1 on 2023-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_created_user_name_user_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JwtCsrfTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jwt_token", models.CharField(max_length=5000)),
                ("csrf_token", models.CharField(max_length=5000)),
            ],
        ),
    ]
