# Generated by Django 4.1.10 on 2023-09-19 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="plan",
        ),
    ]
