# Generated by Django 4.1.10 on 2023-09-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0012_2_8"),
        ("accounts", "0003_remove_user_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The user's Stripe Subscription object, if it exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.subscription",
            ),
        ),
    ]
